// Trenchwars shared TypeScript types — re-exports DTOs generated from spatie/laravel-data.
//
// Source: D-020 LOCKED. The `api.d.ts` sibling file is regenerated by
// `make artisan ARGS="trenchwars:typescript-generate"` (which runs typescript:transform
// inside the web container and then copies the emitted .d.ts into this directory).
//
// Consumers (apps/bot, apps/rcon-worker) import via `@trenchwars/shared-types`:
//
//     import type { UserData } from "@trenchwars/shared-types";
//
// `export type *` keeps the surface to type-only re-exports — `api.d.ts` declares an
// ambient namespace (`declare namespace App.Data { ... }`) so consumers reach types via
// the `App.Data.*` path. We also alias the most common DTOs at the package root so
// consumers don't have to spell out `App.Data.UserData` every time.

/// <reference path="./api.d.ts" />

// Phase 1 DTOs
export type UserData = App.Data.UserData;
export type PlayerData = App.Data.PlayerData;
export type PlayerPrivacyData = App.Data.PlayerPrivacyData;

// Phase 2 DTOs — clan domain
export type ClanData = App.Data.ClanData;
export type ClanTagData = App.Data.ClanTagData;
export type ClanMembershipData = App.Data.ClanMembershipData;
export type ClanInviteData = App.Data.ClanInviteData;
export type ClanApplicationData = App.Data.ClanApplicationData;
export type PublicPlayerData = App.Data.PublicPlayerData;

// Phase 3 DTOs — game catalogue (Game, GameRole, GameMatchType, RoleLimit)
export type GameData = App.Data.GameData;
export type GameRoleData = App.Data.GameRoleData;
export type GameMatchTypeData = App.Data.GameMatchTypeData;
export type GameMatchTypeRoleLimitData = App.Data.GameMatchTypeRoleLimitData;
