// Trenchwars bot — API contract types.
//
// Source: .planning/phases/05-discord-bot-v1/05-08-PLAN.md task 2 (Wave 6).
// Re-exports the spatie/laravel-data DTOs generated by D-020 + adds two
// bot-specific shapes (OutboundRow, BotApiErrorBody) for the surfaces the
// shared package does not cover.
//
// Open question (deferred to Phase 9 polish): should API responses be
// validated at runtime (e.g., via zod) before being typed as `MatchData`?
// For v1 we trust the contract — the web side is the only producer, both
// sides ship from the same monorepo, and TypeScript catches drift at build.

// Re-export Phase 1-4 DTOs from @trenchwars/shared-types.
export type {
    // Phase 1 — identity
    UserData,
    PlayerData,
    PlayerPrivacyData,
    PublicPlayerData,

    // Phase 2 — clans
    ClanData,
    ClanTagData,
    ClanMembershipData,
    ClanInviteData,
    ClanApplicationData,

    // Phase 3 — game catalogue
    GameData,
    GameRoleData,
    GameMatchTypeData,
    GameMatchTypeRoleLimitData,

    // Phase 4 — matches
    MatchData,
    MatchSlotData,
    MatchAccessRuleData,
    MatchResultData,
    MatchMvpData,
    EventData,
    PublicMatchData,
    PublicMatchOccupantData,
} from '@trenchwars/shared-types';

// ---------------------------------------------------------------------------
// Bot-specific contracts not generated from spatie/laravel-data.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Pagination meta — shape of Laravel paginate() meta envelope.
// Used by list endpoints (/matches, /clans) when returning { data, meta }.
// ---------------------------------------------------------------------------

export interface ListMeta {
    current_page: number;
    per_page: number;
    total: number;
    last_page: number;
}

// Shape of a row from `discord_outbound_messages` as returned by
// /api/bot/outbound-messages?status=pending (plan 05-04 BotApiOutboundController).
// The `payload` field is discriminated by `message_type` — concrete payload
// shapes are declared by the consumer in plan 05-11 (worker).
export interface OutboundRow {
    id: string;
    channel_id: string;
    message_type:
        | 'match_announce'
        | 'role_sync'
        | 'tournament_announce'
        | 'tournament_announce_update'
        | 'bracket_result_announce'
        // v1.0 milestone-audit hotfix — Phases 7/8/9 outbound kinds. The web
        // observers (ArticleObserver, MatchResultObserver, DiscordChannel
        // notification channel) enqueue these row kinds in production; the
        // bot dispatcher MUST recognise them to avoid the "Unknown
        // message_type" throw that the audit caught. See
        // .planning/v1.0-MILESTONE-AUDIT.md BLOCKER 1 and
        // .planning/audit-hotfix-bot-dispatcher-SUMMARY.md.
        | 'article_announce'
        | 'match_result_announce'
        | 'user_dm'
        | 'generic';
    status: 'pending' | 'dispatching' | 'sent' | 'failed';
    payload: unknown;
    attempts: number;
    last_error: string | null;
    sent_message_id: string | null;
    causer_user_id: string | null;
    backoff_until: string | null;
    created_at: string;
    updated_at: string;
}

// Shape of the 422 error envelope from /api/bot/* endpoints. The `error` code
// is the canonical machine-readable identifier (e.g. 'match_not_open',
// 'capacity_full', 'tag_mismatch') and `message` is the i18n'd English text.
export interface BotApiErrorBody {
    error: string;
    message: string;
}
